/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Servidor;

import ArchivoBinario.Escritor;
import ArchivoBinario.Lector;
import algoritmoHuffman.ManejadorHuffman;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author Jorge
 */
public class VistaServidor extends javax.swing.JFrame {

    private TP_ChatServidor servidor;
    private ManejadorHuffman manejadorHuffman = new ManejadorHuffman();
    private Lector lectorArchivo = new Lector();
    private Escritor escritorArchivo = new Escritor();

    public VistaServidor(TP_ChatServidor servidor) {
        initComponents();
        this.servidor = servidor;
        setLocationRelativeTo(null);
    }

    public static JTextArea getVistaDescifrada() {
        return vistaDescifrada;
    }
    
    public static JTextArea getVistaCifrada() {
        return vistaCifrada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vistaCifrada = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        generarBt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vistaDescifrada = new javax.swing.JTextArea();
        cargarBt = new javax.swing.JButton();
        enviarBt = new javax.swing.JButton();
        msmClient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaCifrada.setEditable(false);
        vistaCifrada.setColumns(20);
        vistaCifrada.setRows(5);
        jScrollPane1.setViewportView(vistaCifrada);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("Mensaje Cifrado");

        generarBt.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        generarBt.setText("Generar Key");
        generarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtActionPerformed(evt);
            }
        });

        vistaDescifrada.setEditable(false);
        vistaDescifrada.setColumns(20);
        vistaDescifrada.setRows(5);
        jScrollPane2.setViewportView(vistaDescifrada);

        cargarBt.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        cargarBt.setText("Cagar Key");
        cargarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBtActionPerformed(evt);
            }
        });

        enviarBt.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        enviarBt.setText("Enviar");
        enviarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cargarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(msmClient, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enviarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cargarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(msmClient))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBtActionPerformed
        JFileChooser selectorArchivos = new JFileChooser();
        int opcion = selectorArchivos.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            String archivoSeleccionado = selectorArchivos.getSelectedFile().getPath();
            manejadorHuffman.cargarLlave(lectorArchivo.obtenerLlave(archivoSeleccionado));
        }
    }//GEN-LAST:event_cargarBtActionPerformed

    private void enviarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtActionPerformed
        String texto = manejadorHuffman.cifrarTexto(msmClient.getText());
        servidor.enviarMensaje(texto);
    }//GEN-LAST:event_enviarBtActionPerformed

    private void generarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtActionPerformed
        escritorArchivo.guardarLlave(manejadorHuffman.generarLlave());
    }//GEN-LAST:event_generarBtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarBt;
    private javax.swing.JButton enviarBt;
    private javax.swing.JButton generarBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField msmClient;
    private static javax.swing.JTextArea vistaCifrada;
    private static javax.swing.JTextArea vistaDescifrada;
    // End of variables declaration//GEN-END:variables
}
